name: Push To JFROG

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'prod'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout repository
    #  uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Pull image from Docker Hub
      run: docker image pull ubuntu:22.04

    - name: list images
      run: docker image ls

    - name: Image ID
      id: image-id
      uses: s3vt/docker-image-id@v1.0.0
      with:
        image_name: "ubuntu:22.04"
    - name: Print the image ID
      run: echo "Image ID is ${{ steps.image-id.outputs.image_id }}"

    - name: Login to JFrog 
      uses: docker/login-action@v1
      with:
        registry: trialbrlbjt.jfrog.io
        username: ${{ secrets.JFROG_USER_WRITER }}
        password: ${{ secrets.JFROG_PASSWORD_WRITER }}

    - name: Tag image for ACR
      run: docker tag nginxinc/nginx-unprivileged:stable-bookworm-perl acrreddittoastdev.azurecr.io/nginx-unprivileged:stable-bookworm-perl

    - name: Push image to ACR
      run: docker push acrreddittoastdev.azurecr.io/nginx-unprivileged:stable-bookworm-perl
